#1) koristimo oficijalni Python image 
FROM python:3.11-slim

# 2) Postavimo radni direktorijum u kontejneru
WORKDIR /app

# 3) Instaliramo sistemske pakete potrebne za psycopg2  
# gcc- je C kompajler potreban za psycopg2
# libpq-dev je PostgreSQL development biblioteke - potrebno da python moze da koristi postgreSQL
# rm -rf /var/lib/apt/lists/ brisanje apt keša → manji Docker image
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# 4) Kopiramo requirements.txt i instaliramo zavisnosti
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# 5) Kopiramo ceo backend kod u kontejner
COPY . /app/

# 6) Expose porta (nije obavezno)
EXPOSE 8000

# 7) Komanda za pokretanje servera (Gunicorn)
CMD ["gunicorn", "contractai.wsgi:application", "--bind", "0.0.0.0:8000"]